name: 'Run tests with PythonPlot backend'
description: 'variant of tests with PythonPlot'

runs:
  using: 'composite'
  steps:
    - run: julia --project=. -e 'using Pkg; Pkg.add("PythonCall"); Pkg.build("PythonCall")'
      shell: bash
      env:
        PYTHON: ""
    - run: julia --color=yes --project=. -e 'using Pkg; Pkg.test("Pseudospectra"; coverage=true);'
      shell: bash
      env:
        PSPLOTTER: PythonPlot
