## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
   allow_failures:
     - julia: nightly
notifications:
  email: false
before_install:
  - julia -e 'ENV["PYTHON"] = ""; import Pkg; Pkg.add("PyPlot"); Pkg.build("PyPlot")'
  - julia test/primer.jl || true
script:
  - julia --color=yes -e 'import Pkg; Pkg.build("Pseudospectra"); Pkg.test("Pseudospectra"; coverage=true)'
  - julia --color=yes -e 'ENV["PSPLOTTER"] = "PyPlot"; import Pkg; Pkg.test("Pseudospectra"; coverage=true)'
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
