## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - nightly
env:
  - GKS_WSTYPE=png
matrix:
   fast_finish: true
   allow_failures:
     - julia: nightly
notifications:
  email: false
before_install:
  - julia -e 'ENV["PYTHON"] = ""; import Pkg; Pkg.add("PyPlot"); Pkg.build("PyPlot")'
  - julia test/primer.jl || true

script:
  - julia --color=yes -e 'import Pkg; Pkg.build("Pseudospectra"); Pkg.test("Pseudospectra"; coverage=true)'
  - julia --color=yes -e 'ENV["PSPLOTTER"] = "PyPlot"; import Pkg; Pkg.test("Pseudospectra"; coverage=true)'

jobs:
  include:
    - stage: Documentation
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
